<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>    
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
<ItemGroup>
  <PackageReference Include="Ogur.Abstractions" Version="0.2.14-alpha" />
  <PackageReference Include="Ogur.Core" Version="0.2.55-alpha" />
  <PackageReference Include="Stateless" Version="5.15.0" />
  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ogur.Infrastructure\Ogur.Infrastructure.csproj" />
  </ItemGroup>
</Project>
