<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.8" />
    <PackageReference Include="ogur.Abstractions" Version="0.1.0-alpha" />
    <PackageReference Include="ogur.Core"         Version="0.1.0-alpha" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ogur.Infrastructure\Ogur.Infrastructure.csproj" />
    <ProjectReference Include="..\Ogur.Capabilities.Fishing\Ogur.Capabilities.Fishing.csproj" />
  </ItemGroup>
</Project>