<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.0" />
    <PackageReference Include="Ogur.Abstractions" Version="0.1.0-alpha" />
    <PackageReference Include="Ogur.Core"         Version="0.1.0-alpha" />
    <PackageReference Include="Stateless" Version="5.20.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ogur.Infrastructure\Ogur.Infrastructure.csproj" />
    <ProjectReference Include="..\Ogur.Capabilities.Fishing\Ogur.Capabilities.Fishing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Servers\" />
  </ItemGroup>

   <ItemGroup>
    <Resource Include="Assets\Servers\*.png" />
  </ItemGroup>

   <ItemGroup>
     <Page Update="Views\MainWindow.xaml">
       <Generator>MSBuild:Compile</Generator>
       <XamlRuntime>Wpf</XamlRuntime>
       <SubType>Designer</SubType>
     </Page>
   </ItemGroup>

</Project>